const characters = [
  {
    name: "Albedo",
    title: "Kreideprinz",
    vision: "Geo",
    weapon: "Sword",
    nation: "Mondstadt",
    affiliation: "Knights of Favonius",
    rarity: 5,
    constellation: "Princeps Cretaceus",
    birthday: "0000-09-13",
    description:
      "A genius known as the Kreideprinz, he is the Chief Alchemist and Captain of the Investigation Team of the Knights of Favonius.",
    icon: "img/albedo.png",
  },

  {
    name: "Diluc",
    title: "The Dark Side of Dawn",
    vision: "Pyro",
    weapon: "Claymore",
    nation: "Mondstadt",
    affiliation: "Dawn Winery",
    rarity: 5,
    constellation: "Noctua",
    birthday: "0000-04-30",
    description:
      "The tycoon of a winery empire in Mondstadt, unmatched in every possible way.",
    icon: "img/diluc.png",
  },
  {
    name: "Kaeya",
    title: "Frostwind Swordsman",
    vision: "Cryo",
    weapon: "Sword",
    nation: "Mondstadt",
    affiliation: "Knights of Favonius",
    rarity: 4,
    constellation: "Pavo Ocellus",
    birthday: "0000-11-30",
    description:
      "An accomplished swordsman and a strategic thinker in the Knights of Favonius, rumored to hail from beyond Mondstadt.",
    icon: "img/kaeya.png",
  },
  {
    name: "Gorou",
    title: "Canine Warrior",
    vision: "Geo",
    weapon: "Bow",
    gender: "Male",
    nation: "Inazuma",
    affiliation: "Watatsumi Island",
    rarity: 4,
    constellation: "Canis Bellatoris",
    birthday: "0000-05-18",
    description:
      "The great general of Watatsumi Island's forces. He is deeply trusted by his subordinates.",
    icon: "img/gorou.png",
  },
  {
    name: "Xingqiu",
    title: "Juvenile Galant",
    vision: "Hydro",
    weapon: "Sword",
    nation: "Liyue",
    affiliation: "Feiyun Commerce Guild",
    rarity: 4,
    constellation: "Fabulae Textile",
    birthday: "0000-10-09",
    description:
      "A young man carrying a longsword who is frequently seen at book booths. He has a chivalrous heart and yearns for justice and fairness for all.",
    icon: "img/xingqiu.png",
  },
  {
    name: "Kaedehara Kazuha",
    title: "Scarlet Leaves Pursue Wild Waves",
    vision: "Anemo",
    weapon: "Sword",
    nation: "Inazuma",
    affiliation: "The Crux",
    rarity: 5,
    constellation: "Acer Palmatum",
    birthday: "0000-10-29",
    description:
      "If one's heart is empty, all under heaven is empty. But if one's heart is pure, all under heaven is pure.",
    icon: "img/kazuha.png",
  },

  {
    name: "Thoma",
    title: "Protector From Afar",
    vision: "Pyro",
    weapon: "Polearm",
    nation: "Mondstadt",
    affiliation: "Yashiro Commission Kamisato Clan",
    rarity: 4,
    constellation: "Rubeum Scutum",
    birthday: "0000-01-09",
    description:
      'The housekeeper of the Yashiro Commission\'s Kamisato Clan, and a well-known "fixer" in Inazuma.\nFriendly and approachable, Thoma fits in with the crowd easily wherever he is.\nAt first glance, he seems to be a very easygoing person, but he is in fact very responsible. He has an extraordinarily serious side, be it in his work or his interpersonal communications.',
    icon: "img/thoma.png",
  },
  {
    name: "Tighnari",
    title: "Verdant Strider",
    vision: "Dendro",
    weapon: "Bow",
    nation: "Sumeru",
    affiliation: "Gandharva Ville",
    rarity: 5,
    constellation: "Leptailurus Cervarius",
    birthday: "0000-12-29",
    description:
      "\"A message for you. I brought back a specialty from the desert, two packs of honeyed dates, which helps to replenish your energy, whether in the morning or at night. Thank you for your patience in teaching and taking care of Collei. Good luck with your work and best wishes for Collei's studies.\"\n—An anonymously written message left inside a candy box, placed on the watcher's table.",
    icon: "img/tighnari.png",
  },
  {
    name: "Bennett",
    title: "Trial by Fire",
    vision: "Pyro",
    weapon: "Sword",
    nation: "Mondstadt",
    affiliation: "Adventurers' Guild",
    rarity: 4,
    constellation: "Rota Calamitas",
    birthday: "0000-02-29",
    description:
      "A righteous and good-natured adventurer from Mondstadt who's unfortunately extremely unlucky.",
    icon: "img/bennett.png",
  },
  {
    name: "Venti",
    title: "Windborne Bard",
    vision: "Anemo",
    weapon: "Bow",
    nation: "Mondstadt",
    affiliation: "Mondstadt",
    rarity: 5,
    constellation: "Carmen Dei",
    birthday: "0000-06-16",
    description:
      "One of the many bards of Mondstadt, who freely wanders the city's streets and alleys.",
    icon: "img/venti.png",
  },
];

export default characters;
